# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push

jobs:
  somethest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        binary: [geth, bsc, polygon]

    outputs:
      tags: ${{ steps.meta.outputs.outs }}

    steps:
      - name: some echo
        id: meta
        run: echo '::set-output name=outs::${{ matrix.binary }}-latest'

  download:
    runs-on: ubuntu-latest
    needs: somethest
    steps:
      - name: echo blah
        run: echo ${{needs.somethest.outputs.outs]}}


