name: build
on:
  workflow_dispatch:
    inputs:
      flavors:
        description: 'JSON-formatted list of flavors to build'
        required: true
        default: '["geth","bsc","polygon"]'
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary: ${{ fromJSON(github.event.inputs.flavors) }}
    steps:
      - id: print
        run: |
          OUT="blahblah
          blibloh
          bluh"
          OUT="${OUT//'%'/'%25'}"
          OUT="${OUT//$'\n'/' '}"
          OUT="${OUT//$'\r'/' '}"
          echo "${{ matrix.binary }}=$OUT"
          echo "${{ matrix.binary }}=$OUT" >> $GITHUB_OUTPUT

    outputs:
      geth: ${{ steps.print.outputs.geth }}
      bsc: ${{ steps.print.outputs.bsc }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      run: |
        echo ${{ needs.job1.outputs.geth }}
        echo ${{ needs.job1.outputs.bsc }}
