name: build
on:
  workflow_dispatch:
    inputs:
      flavors:
        description: 'JSON-formatted list of flavors to build'
        required: true
        default: '["geth","bsc","polygon"]'
        type: string

jobs:
  job2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary: ${{ fromJSON(github.event.inputs.flavors) }}
    steps:
      run: |
        OUT="blahblah
        blibloh
        bluh"
        OUT="${OUT//'%'/'%25'}"
        OUT="${OUT//$'\n'/' '}"
        OUT="${OUT//$'\r'/' '}"
        echo "${{ matrix.binary }}=$OUT"
        echo "${{ matrix.binary }}=$OUT" >> $GITHUB_OUTPUT
